name: health
description: A new fitness app

version: 0.0.1+5

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  
  after_layout: ^1.0.7
  flutter_datetime_picker: ^1.4.0
  shared_preferences:
  intl: any
  http: 
  flutter_swiper: 
  scoped_model: ^1.0.1
  image_picker: any
  dio: ^3.0.9
  google_maps_flutter: ^0.5.28+1
  cupertino_icons: ^0.1.2
  auto_size_text: ^1.0.0
  geolocator: ^5.3.2+2
  flutter_circular_chart: ^0.1.0
  screenshot_share_image: any
  firebase_auth: ^0.14.0+5
  firebase_storage: 3.0.3
  cloud_firestore: any
  url_launcher: ^5.0.1
  fl_chart: ^0.0.8
  cached_network_image: ^2.0.0
  photo_view: ^0.4.2
  fluttertoast: ^3.1.0
  flutter_picker_view: ^1.0.0
  firebase_messaging: ^6.0.9
  firebase_core: ^0.4.3+1
  flutter_rating_bar: ^3.0.0
  flutter_spinkit: ^4.0.0
  share: ^0.6.2+3
  flutter_blue:
    git: https://github.com/adham-ashraf77/flutter_blue.git
  rxdart: any

  vector_math: ^2.0.8
  pedometer: ^1.2.5
  flutter_local_notifications: ^1.4.4+2
  app_settings: ^4.0.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/lang/
    - assets/
